version: '3.9'

services:
  vivelibre-token:
    container_name: vivelibre-token
    image: vivelibre-token:1.0
    build: .
    ports: 
      - 127.0.0.1:8080:8080
    environment:
      - DATABASE_URL=jdbc:posrgresql://vivelibre-db:5432/ejemplo_token
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1234
    volumes:
      - ./vivlibre-token:/app
    depends_on:
      - vivelibre-db

  vivelibre-db:
    container_name: vivelibre-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ejemplo_token
    volumes: 
      - './SQL/initial_script.sql:/docker-entrypoint-initdb.d/initial_script.sql'
